#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v13
# autospec commit: 2659038
#
Name     : open-lldp
Version  : 1.1.1
Release  : 22
URL      : https://github.com/intel/openlldp/archive/v1.1.1/openlldp-1.1.1.tar.gz
Source0  : https://github.com/intel/openlldp/archive/v1.1.1/openlldp-1.1.1.tar.gz
Summary  : A Shared library to communicate with lldpad
Group    : Development/Tools
License  : GPL-2.0
Requires: open-lldp-bin = %{version}-%{release}
Requires: open-lldp-lib = %{version}-%{release}
Requires: open-lldp-license = %{version}-%{release}
Requires: open-lldp-man = %{version}-%{release}
Requires: open-lldp-services = %{version}-%{release}
BuildRequires : file
BuildRequires : flex
BuildRequires : pkgconfig(libconfig)
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : pkgconfig(systemd)
BuildRequires : readline-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Link Layer Discovery Protocol (LLDP) Agent with
Data Center Bridging (DCB) for Intel(R) Network Connections
===========================================================

%package bin
Summary: bin components for the open-lldp package.
Group: Binaries
Requires: open-lldp-license = %{version}-%{release}
Requires: open-lldp-services = %{version}-%{release}

%description bin
bin components for the open-lldp package.


%package dev
Summary: dev components for the open-lldp package.
Group: Development
Requires: open-lldp-lib = %{version}-%{release}
Requires: open-lldp-bin = %{version}-%{release}
Provides: open-lldp-devel = %{version}-%{release}
Requires: open-lldp = %{version}-%{release}

%description dev
dev components for the open-lldp package.


%package lib
Summary: lib components for the open-lldp package.
Group: Libraries
Requires: open-lldp-license = %{version}-%{release}

%description lib
lib components for the open-lldp package.


%package license
Summary: license components for the open-lldp package.
Group: Default

%description license
license components for the open-lldp package.


%package man
Summary: man components for the open-lldp package.
Group: Default

%description man
man components for the open-lldp package.


%package services
Summary: services components for the open-lldp package.
Group: Systemd services
Requires: systemd

%description services
services components for the open-lldp package.


%prep
%setup -q -n openlldp-1.1.1
cd %{_builddir}/openlldp-1.1.1
pushd ..
cp -a openlldp-1.1.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720126567
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%reconfigure --disable-static
make  %{?_smp_mflags}
unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%reconfigure --disable-static
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720126567
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/open-lldp
cp %{_builddir}/openlldp-%{version}/COPYING %{buildroot}/usr/share/package-licenses/open-lldp/3537c2a1bd2083966623fa31d8598429383bbf22 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3 BASH_COMPLETION_DIR=/usr/share/bash-completion/completions/
popd
GOAMD64=v2
%make_install BASH_COMPLETION_DIR=/usr/share/bash-completion/completions/
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/dcbtool
/V3/usr/bin/lldpad
/V3/usr/bin/lldptool
/V3/usr/bin/vdptool
/usr/bin/dcbtool
/usr/bin/lldpad
/usr/bin/lldptool
/usr/bin/vdptool

%files dev
%defattr(-,root,root,-)
/usr/include/lldpad/clif.h
/usr/include/lldpad/clif_msgs.h
/usr/include/lldpad/clif_sock.h
/usr/include/lldpad/dcb_types.h
/usr/include/lldpad/dcbnl.h
/usr/include/lldpad/lldp_8021qaz_cmds.h
/usr/include/lldpad/lldp_8023_cmds.h
/usr/include/lldpad/lldp_basman_cmds.h
/usr/include/lldpad/lldp_dcbx_cmds.h
/usr/include/lldpad/lldp_evb_cmds.h
/usr/include/lldpad/lldp_mand_cmds.h
/usr/include/lldpad/lldp_med_cmds.h
/usr/include/lldpad/lldp_util.h
/usr/include/lldpad/lldpad.h
/usr/include/lldpad/lldpad_status.h
/usr/include/lldpad/netlink.h
/usr/include/lldpad/qbg_vdp_cmds.h
/usr/include/lldpad/rtnetlink.h
/usr/lib64/liblldp_clif.so
/usr/lib64/pkgconfig/liblldp_clif.pc
/usr/lib64/pkgconfig/lldpad.pc
/usr/share/man/man3/liblldp_clif-vdp22.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/liblldp_clif.so.1.0.0
/usr/lib64/liblldp_clif.so.1
/usr/lib64/liblldp_clif.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/open-lldp/3537c2a1bd2083966623fa31d8598429383bbf22

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/dcbtool.8
/usr/share/man/man8/lldpad.8
/usr/share/man/man8/lldptool-app.8
/usr/share/man/man8/lldptool-dcbx.8
/usr/share/man/man8/lldptool-ets.8
/usr/share/man/man8/lldptool-evb.8
/usr/share/man/man8/lldptool-evb22.8
/usr/share/man/man8/lldptool-med.8
/usr/share/man/man8/lldptool-pfc.8
/usr/share/man/man8/lldptool-vdp.8
/usr/share/man/man8/lldptool.8
/usr/share/man/man8/vdptool.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/lldpad.service
/usr/lib/systemd/system/lldpad.socket
